### ISSUE TITLE
Typo in run-in-docker.sh

### ISSUE THREAD

**Issue by Rob2U** [konstantinjdobler/nlp-research-template#40]
Running bash ./scripts/run-in-docker.sh bash leads to:
```
image: rob2u/yolo-devcontainer:1.0.0 
command: e
gpus: none
WANDB_API_KEY not found
/usr/local/bin/_entrypoint.sh: line 24: exec: e: not found
```
This is probably due to a spelling error (`set e` instead of `set -e`) (if [this](https://stackoverflow.com/questions/3474526/stop-on-first-error)) behaviour is intended )

**Comment by konstantinjdobler** [comment]
Good catch!
