### ISSUE TITLE
Not possible to install packages inside devcontainer

### ISSUE THREAD

**Issue by Rob2U** [konstantinjdobler/nlp-research-template#42]
When I try to install a package for my mamba environment with:
`mamba install ultralytics`
I receive the error message:
critical libmamba filesystem error: cannot copy symlink: Permission denied [/home/mamba/.mamba/pkgs/libpng-1.6.39-h753d276_0/bin/libpng-config] [/opt/conda/envs/research/bin/libpng-config]
If I try to create a new environment using 
`mamba create --name yolov8_train python=3.10`
I again receive
critical libmamba filesystem error: cannot create directories: Permission denied [/opt/conda/envs/yolov8_train/conda-meta]

**Comment by Rob2U** [comment]
adding "-u", "0" to the "runArgs" inside the .devcontainer.json solved the issue

**Comment by Rob2U** [comment]
by setting the user to 1000 (the mamba user) instead of 0 it is also not necessary to be the root user.

**Comment by konstantinjdobler** [comment]
Yes that works, keep in mind though that any files you create while in the devcontainer will belong to the mamba user and not to your real user on the host. There is no really great solution here, we can add this at the end of the `Dockerfile`:

```
# Give permissions to micromamba for all users so that you can do `mamba install` even when using docker run -u $(id -u):$(id -g)
# makes the image much larger though
USER root
# chown $MAMBA_USER:$MAMBA_USER ${MAMBA_ROOT_PREFIX} && 
RUN chmod -R 777 ${MAMBA_ROOT_PREFIX} 
USER $MAMBA_USER
```

and installing works with any user but makes the image quite a bit larger (8GB in the nlp-research-template)

**Comment by konstantinjdobler** [comment]
In #46 installing should work out-of-the-box now. Important: the `MAMBA_USER_ID` has changed from 1000 to 57439.
